/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Intersection of `subject` and `clipping`. */
export declare function intersection(subject: number[][][] | number[][][][], clipping: number[][][] | number[][][][]): number[][][][] | null
/** Union of `subject` and `clipping`. */
export declare function union(subject: number[][][] | number[][][][], clipping: number[][][] | number[][][][]): number[][][][] | null
/** `subject` minus `clipping`. */
export declare function diff(subject: number[][][] | number[][][][], clipping: number[][][] | number[][][][]): number[][][][] | null
/** Symmetric difference of `subject` and `clipping`. */
export declare function xor(subject: number[][][] | number[][][][], clipping: number[][][] | number[][][][]): number[][][][] | null
